[package]
name = "torctl"
version = "0.1.0"
edition = "2021"
authors = ["Gabriele Pongelli"]
license = "MIT"
repository = "https://github.com/gabrielepongelli/torctl"
readme = "README.md"

[dependencies]
